### ISSUE TITLE
Problem running*     python ridgesfm.py scene.n=0 scene.frameskip=10

### ISSUE THREAD

**Issue by yoichims** [facebookresearch/RidgeSfM#1]
Hi I am having some issues when running
python ridgesfm.py scene.n=0 scene.frameskip=10

I am using Ubuntu 18.04

Traceback (most recent call last):
  File "ridgesfm.py", line 52, in my_app
    s = utils.load_scene(cfg, net)
  File "/home/yoichims/.local/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/home/yoichims/Research/RidgeSfM/ridgesfm/utils.py", line 1439, in load_scene
    f'{cfg.scenes}/*/*frameskip={cfg.scene.frameskip}-*.pth'))[cfg.scene.n]
IndexError: list index out of range

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by btgraham** [comment]
Have you downloaded and preprocessed the ScanNet dataset?
If so, there should be files such as 
```
RidgeSfM/ridgesfm/data/scannet/test_scenes/0707_00/seq=0707_00-maxframes=300-frameskip=10-start=1.pth
```
Alternatively, try extracting
https://drive.google.com/file/d/1OP2IYrsbtP2gyEfXPIUAmkBTp-YWqRzS/view?usp=sharing
to RidgeSfM/ridgesfm/data and check that 
```
RidgeSfM/ridgesfm/data/scannet/test_scenes/0707_00/seq=0707_00-maxframes=300-frameskip=10-start=1.pth
```
exists.

**Comment by Kewenjing1020** [comment]
hi @btgraham , after run `python prepare_scene.py `, I get files.pth in the data directory. Is this the file you mentioned?

**Comment by yoichims** [comment]
Thank you for the help. That solved the issue.
It was difficult to understand the test_scenes directory structure.
I downloaded your google drive files and worked.

     
I have another issue but that is regarding my python version.
