### ISSUE TITLE
ImportError: _C.cython-38-x86_64-linux-gnu.so: undefined symbol:

### ISSUE THREAD

**Issue by jakeju92** [facebookresearch/RidgeSfM#3]
Hi, I'm trying to make this repo run on my pc. I have followed all the instructions in the README.md file. However, after I run this command: `python ridgesfm.py scene.n=0 scene.frameskip=10`. This error message occurs:
```
ImportError: _C.cython-38-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv
```
I also made a screenshot for more info:
![image](https://user-images.githubusercontent.com/5748897/118499054-2bd0ab00-b759-11eb-8bdd-def875132c72.png)

Anyone could help me to solve it?

OS: Ubuntu 20.04LTS
Python version: 3.8
torch version: 1.8.1
torchvision version: 0.9.1
GCC version: 7.5
pytorch3d version: 0.3.0

**Comment by btgraham** [comment]
The error is occuring when pytorch3d is imported, i.e. it will also trigger if you run 
`python -c 'import pytorch3d'`
from the command line. You may be able to get help from https://github.com/facebookresearch/pytorch3d
