### ISSUE TITLE
Problem running python ridgesfm.py scene.n=0 scene.frameskip=1

### ISSUE THREAD

**Issue by jasonhongpro** [facebookresearch/RidgeSfM#4]
Hello , I kept getting this warning when trying to run the example. I followed all the instructions, used the data from your google drive, tried change config in @hydra.main(), nothing works.

/Desktop/ridgesfm# python ridgesfm.py scene.n=0 scene.frameskip=1
ridgesfm.py:20: UserWarning: 
config_path is not specified in @hydra.main().
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_hydra_main_config_path for more information.
  @hydra.main(config_name='conf/ransac.yaml')
Could not override 'scene.n'.
To append to your config use +scene.n=0
Key 'scene' is not in struct
    full_key: scene
    object_type=dict

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

Does it has something to do with newer hydra version? Ive tried both 1.0 and 1.1, the warning is still there.
 
Thank you

**Comment by btgraham** [comment]
Please 'git pull' and retry.
