### ISSUE TITLE
default config running failed with ScanNet

### ISSUE THREAD

**Issue by AddASecond** [facebookresearch/RidgeSfM#5]
I follow the instructions here to run RidgeSfM on ScanNet 0707 data

> To download one test scene:
> Download scannet.zip to RidgeSfM/ridgesfm/data and check that RidgeSfM/ridgesfm/data/scannet/test_scenes/0707_00/seq=0707_00-maxframes=300-frameskip=10-start=1.pth exists.
> Run python ridgesfm.py scene.n=0 scene.frameskip=10

but the program crash when saving pose,
giving the following message "a matrix has trace outside valid range [-1 -eps 3+ eps]"
<img width="1024" alt="840e604eb13c44a8e071576188638f18" src="https://user-images.githubusercontent.com/12587374/128627537-cd861fcc-bd3f-4062-9f93-21c506877b91.png">

**Comment by btgraham** [comment]
Sorry, but I cannot replicate this. I get
```
Timing for 20 iterations: 38.13965s = 20 x 1.90698s

torch.Size([5561400, 6]) torch.Size([100000, 6])
pcl_point_cloud_rmse_loss_scaled 0.21577051281929016
pcl_rmse_depth_scaled 0.21645542979240417
pcl_cam_center_err_interp_scaled 0.17502082884311676
pcl_cam_angle_err_interp_scaled 3.287416458129883
```

**Comment by AddASecond** [comment]
> Sorry, but I cannot replicate this. I get
> 
> ```
> Timing for 20 iterations: 38.13965s = 20 x 1.90698s
> 
> torch.Size([5561400, 6]) torch.Size([100000, 6])
> pcl_point_cloud_rmse_loss_scaled 0.21577051281929016
> pcl_rmse_depth_scaled 0.21645542979240417
> pcl_cam_center_err_interp_scaled 0.17502082884311676
> pcl_cam_angle_err_interp_scaled 3.287416458129883
> ```

Thanks， after running the following command I have obtain the similar results as yours

> Run bash prepare_scannet.sh in ridgesfm/data/
