### ISSUE TITLE
Question not issue

### ISSUE THREAD

**Issue by nesquik011** [facebookresearch/RidgeSfM#6]
do i need two cameras or just one  ?  and is it possible to make live point cloud from live video ?

**Comment by btgraham** [comment]
You need a sequence of images from one camera.
The program runs offline, not on live video.

**Comment by nesquik011** [comment]
@btgraham thank you for reply 

if i used 4K video will the resolution or accuracy be better ?  

how short the video could be ? is it possible to be 1 sec ? for example, i want to record many videos of an object then align the point coulds so each video would be like 1 sec
